### ISSUE TITLE
Calcul du score

### ISSUE THREAD

**Issue by Tiplok** [Tiplok/M1S2_PJI#2]
Le calcul du score semble incorrect, lorsqu'on plante une forêt et qu'on l'a retire, le score augmente ou diminue mais ne revient pas le même (alors que ça devrait être le cas). Il est possible qu'il existe d'autres problèmes dans le calcul du score, il n'a pas encore été vérifié complétement.

**Comment by PPG-RadiUm** [comment]
Calcul du score résolu sauf dans le cas d'une déforestation totale.
On peut résoudre en contournant le problème en partant du principe que le score retourne à son état initial mais ce n'est pas optimal.

**Comment by PPG-RadiUm** [comment]
Problème résolu
